# Simple workflow for deploying static content to GitHub Pages
name: Deploy to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Add additional jobs here!!

  # End additional job steps!!
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use Node.js version 14 or adjust based on your project requirements

      - name: Install dependencies
        run: npm install  # If you have a package.json file, installs dependencies (skip if not using Node)

      # Add steps here!!
      - name: Lint HTML files
        run: |
          npm install -g htmlhint
          htmlhint **/*.html
      # End additional steps!!

      - name: Build project
        run: npm run build  # Build command (adjust if necessary or skip if you don’t have a build process)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Directory where your site’s build files are located; adjust if necessary
