# Simple workflow for PRs in GitHub
name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Linting job to check for code formatting and standards
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: CSS Lint
        uses: github/super-linter@v5
        env:
          VALIDATE_CSS: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run HTML Lint
        run: |
          npm install -g htmlhint
          htmlhint **/*.html

  # New job for lightweight testing
  test:
    name: Test Code
    runs-on: ubuntu-latest
    needs: lint # Ensures linting completes first
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify essential files exist
        run: |
          if [ ! -f "README.md" ]; then
            echo "Error: README.md is missing!" >&2
            exit 1
          fi
          echo "README.md exists."

      - name: Test for valid HTML files
        run: |
          if ! find . -name "*.html" | grep -q .; then
            echo "Error: No HTML files found!" >&2
            exit 1
          fi
          echo "HTML files found and valid!"

      - name: Run custom tests
        run: echo "Custom tests here - Replace with your testing command"
