name: GitHub Actions PR Workflow

on:
  # Runs on pull requests to main branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (since cspell is a Node.js tool)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install `cspell` globally
      - name: Install cspell
        run: |
          npm install -g cspell  # Install the cspell spell checker globally

      # Step 4: Run Spell Checking
      - name: Run Spell Checking
        run: |
          cspell "**/*.md" "**/*.html" "**/*.txt"  # Check for spelling errors in markdown, html, and text files